exalsius/exalsius-cli

.vscode/launch.json
.vscode/settings.json

chore: Added project-specific vscode settings

---

.pre-commit-config.yaml

Bumped isort version 5.13.2 -> 6.0.1

---

exalsius/cli/commands/workspaces.py

fix: Fixed get command indent

---

exalsius/cli/config.py
pyproject.toml
uv.lock

Implemented CLI config management and added a configuration for default cluster setting.

feat: CLI config management

---

exalsius/cli/app.py
exalsius/cli/commands/clusters.py
exalsius/cli/commands/workspaces.py
exalsius/cli/config.py
exalsius/core/operations/workspaces_operations.py
exalsius/core/services/workspaces_services.py
pyproject.toml
uv.lock

Implemented add and delete for workspaces

feat: workspace add delete

---

exalsius/cli/commands/clusters.py
exalsius/cli/commands/workspaces.py
exalsius/core/operations/clusters_operations.py
exalsius/core/operations/workspaces_operations.py
exalsius/core/services/clusters_service.py
exalsius/core/services/workspaces_services.py
exalsius/display/clusters_display.py

Implemented showing available resources for a cluster

feat: cluster available resources

---

exalsius/display/workspaces_display.py

Improved robustness of workload result printing

fix: improved robustness of workload result printing

---

exalsius/cli/commands/workspaces.py
exalsius/core/services/workspaces_services.py
exalsius/display/workspaces_display.py

feat: display workspace access info

---

exalsius/cli/commands/workspaces.py
exalsius/core/services/workspaces_services.py
exalsius/display/workspaces_display.py

Fixed display message when workspaces are deleted

fix: display message when workspaces are deleted

---

exalsius/cli/app.py
exalsius/cli/commands/login.py
exalsius/cli/config.py
exalsius/core/models/login.py
exalsius/core/operations/clusters_operations.py
exalsius/core/operations/login_operation.py
exalsius/core/services/base.py
exalsius/core/services/login_service.py
exalsius/display/login_display.py

implemented basic login mechanism

feat: implemented basic login mechanism

---

exalsius/core/operations/workspaces_operations.py

Increased default resources for workspaces

chore: increased default resources for workspaces

---

exalsius/cli/commands/workspaces.py
exalsius/core/models/workspaces.py
exalsius/core/operations/workspaces_operations.py
exalsius/core/services/workspaces_services.py

implemented workspace type options. Can be 'pod' or 'jupyter'.

feat: implemented workspace type options

---

exalsius/core/operations/workspaces_operations.py

fix: hotfixed resource definition for workspace. Needs fixing in API

fix: hotfixed resource definition for workspace

---

exalsius/cli/app.py
exalsius/cli/auth/cli.py
exalsius/cli/auth/display.py
exalsius/cli/auth/models.py
exalsius/cli/auth/operations.py
exalsius/cli/auth/service.py

feat: implemented auth0 logout flow. Improved UX: user feedback when running commands while not logged in

feat: implemented auth0 logout flow. Improved UX: user feedback when running commands while not logged in

---

exalsius/cli/auth/cli.py
exalsius/cli/auth/display.py
exalsius/cli/auth/service.py
exalsius/cli/utils.py

- Implemented silent browser preference with fallback to default browser opening and another fallback to terminal URL display
- implemented auto browser opening within the device code authentication flow

feat: implemented auto browser opening within the device code authentication flow

---

exalsius/cli/auth/cli.py

added logging to cli login flow

chore: added logging to cli login flow

---

exalsius/cli/auth/cli.py

changes logging from info to debug

chore: changes logging from info to debug

---

exalsius/auth/cli.py
exalsius/auth/service.py
exalsius/core/commons/commands.py
exalsius/core/commons/models.py

proper handling of empty response on token revoke against the auth0 api

fix: proper handling of empty response on token revoke

---

exalsius/offers/cli.py
exalsius/offers/display.py

chore: removed the grouping by GPU type. gpu offers are shown in one table now.

chore: removed the grouping by GPU type. gpu offers are shown in one table now.

---

exalsius/nodes/commands.py
exalsius/nodes/models.py
exalsius/nodes/service.py

fix: fixed bug where key path instead of key content was encoded and sent to api

fix: fixed bug where key path instead of key content was encoded and sent to api

---

exalsius/app.py
exalsius/services/__init__.py
exalsius/services/cli.py
exalsius/services/commands.py
exalsius/services/display.py
exalsius/services/models.py
exalsius/services/service.py
exalsius/workspaces/cli.py

implemented commands for service endpoints

feat: implemented commands for service endpoints

---

exalsius/services/cli.py
exalsius/services/commands.py
exalsius/services/display.py
exalsius/services/models.py
exalsius/services/service.py

feat: added services commands to support interaction with the service endpoints

feat: added services commands to support interaction with the service endpoints

---

exalsius/clusters/cli.py
exalsius/clusters/commands.py
exalsius/clusters/models.py
exalsius/clusters/service.py
exalsius/core/commons/commands.py
exalsius/core/commons/models.py

feat: added command to import kubeconfig and story it locally in .kube folder

feat: added command to import kubeconfig and story it locally in .kube folder

---

exalsius/workspaces/cli.py
exalsius/workspaces/commands.py
exalsius/workspaces/models.py
exalsius/workspaces/service.py

fix: fixed workspace creation to support the new templates structure.

fix: fixed workspace creation to support the new templates structure.

---

exalsius/clusters/cli.py
exalsius/clusters/models.py
exalsius/clusters/service.py
exalsius/config.py

Added support for default cluster labels on cluster creation controlling services that are installed when cluster is deployed. Remove default cluster settings.

feat: added support for default cluster labels

---

exalsius/clusters/cli.py
exalsius/clusters/models.py
exalsius/clusters/service.py
exalsius/config.py

This PR enables the configuration of observability for a cluster by setting a particular label.

feat: configuration option for deploying observability into cluster

---

exalsius/offers/cli.py
exalsius/offers/service.py

- fixed offers listing
- added sanity checking

chore: fixed offers listing. Added sanity checking.

---

exalsius/clusters/cli.py
exalsius/clusters/display.py
exalsius/clusters/models.py
exalsius/clusters/service.py
exalsius/config.py
exalsius/offers/display.py
exalsius/services/cli.py

implemented a table view for the clusters nodes

feat: implemented a table view for the clusters nodes

---

exalsius/clusters/cli.py
exalsius/clusters/display.py
exalsius/nodes/cli.py
exalsius/nodes/display.py

- chore: remove node ID column
- chore: added sane defaults for hostname and amount
- chore: renamed command to add nodes to cluster to plural
- chore: fixed cluster creation message
- chore: set default cluster type to REMOTE
- chore: consolidated nodes table view

chore/minor UI fixes

---

exalsius/clusters/display.py
exalsius/workspaces/cli.py
exalsius/workspaces/display.py

chore: minor ui fixes

---

exalsius/app.py
exalsius/auth/cli.py
exalsius/auth/commands.py
exalsius/auth/display.py
exalsius/auth/service.py
exalsius/offers/cli.py
tests/unit/auth/test_cli.py
tests/unit/auth/test_commands.py
tests/unit/auth/test_display.py
tests/unit/auth/test_service.py

- fixed feedback message for deployment token 
- UI/UX of command
- extended test cases 
- fixed logout procedure

fix: fixed auth tests and deployment token

---

exalsius/auth/cli.py
exalsius/auth/service.py
tests/unit/auth/test_service.py

This PR fixes tests after auth0 changes.

fix: adapt tests

---

exalsius/workspaces/cli.py
exalsius/workspaces/devpod/models.py
exalsius/workspaces/jupyter/cli.py
exalsius/workspaces/llminference/cli.py
exalsius/workspaces/llminference/models.py
exalsius/workspaces/marimo/__init__.py
exalsius/workspaces/marimo/cli.py
exalsius/workspaces/marimo/models.py
exalsius/workspaces/marimo/service.py

added marimo workspace and fixed docker image defaults

feat: added marimo workspace and fixed docker image defaults

---

exalsius/workspaces/marimo/cli.py
exalsius/workspaces/marimo/models.py

This PR adds an option to set a password for a marimo workspace.

fix(marimo): introduce CLI flag for configuring marimo workspace password

---

exalsius/workspaces/diloco/default_config.yml

added diloco workspace torch compile params

feat: added diloco workspace torch compile params
